In [1]:
import numpy as np
import pandas as pd
#stemmin class from nltk
from nltk.stem.porter import PorterStemmer
#count vectorizor
from sklearn.feature_extraction.text import CountVectorizer
#cosine similarity to calculate that similarity measure between movies
from sklearn.metrics.pairwise import cosine_similarity


In [2]:
#Reading the dataset
df=pd.read_csv(r"C:\Users\karth\Downloads\movies_dataset.csv")

In [3]:
df.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                                tags  
0  in the 22nd century, a paraplegic marine is di...  
1  captain barbossa, long believed to be dead, ha...  
2  a cryptic message from bond’s past sends him o...  
3  following the death of district attorney harve...  
4  john carter is a war-weary, former military ca...

In [4]:
df['tags'][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron'

In [5]:
ps=PorterStemmer()

In [6]:
# Defining stemmin class
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return" ".join(y)

In [7]:
ps.stem('programmers')

'programm'

In [8]:
#Example of how words are reduced through stemming
# choose some words to be stemmed
#stemming example. A stemmeing algorithm reduces the words to the root/base word.
words = ["program", "programs", "programmer", "programming", "programmers"]
 
for w in words:
    print(w, " : ", ps.stem(w))

program  :  program
programs  :  program
programmer  :  programm
programming  :  program
programmers  :  programm


In [9]:
'''for larger datasets ".apply(stem)" is more faster than Iterate over rows.
'''
#df['tags']=df['tags'].apply(stem)

'for larger datasets ".apply(stem)" is more faster than Iterate over rows.\n'

In [10]:
# Iterate over rows.
for index, row in df.iterrows():
    print(index)  # (optional debug line)
    df.loc[index, 'tags'] = stem(row['tags'])


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

In [11]:
cv=CountVectorizer(max_features=5000,stop_words='english')
vectors=cv.fit_transform(df['tags']).toarray()

In [12]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4806, 5000))

In [13]:
# It prints all the reduced words
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      shape=(5000,), dtype=object)

In [ ]:
# Calculating cosine similarity
similarity=cosine_similarity(vectors)

In [ ]:
# Calculating the similarity of 0 vector
similarity[0]

array([1.        , 0.08346223, 0.0860309 , ..., 0.04499213, 0.        ,
       0.        ], shape=(4806,))

In [16]:
similarity[1]

array([0.08346223, 1.        , 0.06063391, ..., 0.02378257, 0.        ,
       0.02615329], shape=(4806,))

In [17]:
similarity.shape

(4806, 4806)

In [ ]:

df[df['title'].str.contains("The Lord of the Rings: The Fellowship")]

movie_id                                              title  \
262       120  The Lord of the Rings: The Fellowship of the Ring   

                                                  tags  
262  young hobbit frodo baggins, after inherit a my...

In [20]:
sorted(similarity[262])

[np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float6

In [21]:
for count, value in enumerate(similarity[262]):
    print(count, value)

0 0.10650358071057624
1 0.09007546982220897
2 0.06963575181639443
3 0.05947010334500525
4 0.15322409370161832
5 0.10527936095153945
6 0.04885967564883423
7 0.1385663269313568
8 0.09589266029707681
9 0.07918075824648958
10 0.14532958974404492
11 0.15322409370161832
12 0.1462979547282512
13 0.03641785203646149
14 0.126155140059354
15 0.13561270072416204
16 0.042601432284230495
17 0.14546434136292807
18 0.12294604428906897
19 0.35305338554802046
20 0.2583768965864695
21 0.1553638665664663
22 0.3484365738222833
23 0.11791665765914455
24 0.12951986753290365
25 0.041293962759267534
26 0.04152273992686998
27 0.11768446184934013
28 0.04716666306365782
29 0.07018624063435963
30 0.16232693100931947
31 0.051502620262460476
32 0.12068965517241377
33 0.07878385971583353
34 0.0
35 0.13401406685472436
36 0.09897594780811197
37 0.10650358071057624
38 0.09847982464479191
39 0.13316902848554255
40 0.12456821978060995
41 0.13407108198891604
42 0.018952451089472584
43 0.05515973485146915
44 0.136896419548

In [22]:
list(enumerate(similarity[262]))

[(0, np.float64(0.10650358071057624)),
 (1, np.float64(0.09007546982220897)),
 (2, np.float64(0.06963575181639443)),
 (3, np.float64(0.05947010334500525)),
 (4, np.float64(0.15322409370161832)),
 (5, np.float64(0.10527936095153945)),
 (6, np.float64(0.04885967564883423)),
 (7, np.float64(0.1385663269313568)),
 (8, np.float64(0.09589266029707681)),
 (9, np.float64(0.07918075824648958)),
 (10, np.float64(0.14532958974404492)),
 (11, np.float64(0.15322409370161832)),
 (12, np.float64(0.1462979547282512)),
 (13, np.float64(0.03641785203646149)),
 (14, np.float64(0.126155140059354)),
 (15, np.float64(0.13561270072416204)),
 (16, np.float64(0.042601432284230495)),
 (17, np.float64(0.14546434136292807)),
 (18, np.float64(0.12294604428906897)),
 (19, np.float64(0.35305338554802046)),
 (20, np.float64(0.2583768965864695)),
 (21, np.float64(0.1553638665664663)),
 (22, np.float64(0.3484365738222833)),
 (23, np.float64(0.11791665765914455)),
 (24, np.float64(0.12951986753290365)),
 (25, np.float64

In [23]:
sorted(list(enumerate(similarity[262])),reverse=True)

[(4805, np.float64(0.04004808657316366)),
 (4804, np.float64(0.07503224734841288)),
 (4803, np.float64(0.018208926018230744)),
 (4802, np.float64(0.03790490217894517)),
 (4801, np.float64(0.14024885950870325)),
 (4800, np.float64(0.16985121921200538)),
 (4799, np.float64(0.021300716142115247)),
 (4798, np.float64(0.13675713199027156)),
 (4797, np.float64(0.0)),
 (4796, np.float64(0.031846487764924096)),
 (4795, np.float64(0.05685735326841775)),
 (4794, np.float64(0.15161960871578065)),
 (4793, np.float64(0.0)),
 (4792, np.float64(0.0)),
 (4791, np.float64(0.02285751604412472)),
 (4790, np.float64(0.04716666306365782)),
 (4789, np.float64(0.032826608214930636)),
 (4788, np.float64(0.0)),
 (4787, np.float64(0.11146270717723435)),
 (4786, np.float64(0.07530940414109723)),
 (4785, np.float64(0.1592324388246205)),
 (4784, np.float64(0.0)),
 (4783, np.float64(0.11461365101225056)),
 (4782, np.float64(0.0)),
 (4781, np.float64(0.07074999459548673)),
 (4780, np.float64(0.14412753434733405)),
 

In [24]:
sorted(list(enumerate(similarity[262])),reverse=True, key=lambda x:x[1])

[(262, np.float64(1.0)),
 (98, np.float64(0.46600351662203704)),
 (330, np.float64(0.42548147169838163)),
 (19, np.float64(0.35305338554802046)),
 (22, np.float64(0.3484365738222833)),
 (329, np.float64(0.29821002598961355)),
 (1622, np.float64(0.2913428162916919)),
 (20, np.float64(0.2583768965864695)),
 (1993, np.float64(0.25231028011870793)),
 (790, np.float64(0.24802326206836478)),
 (3676, np.float64(0.240288519438982)),
 (292, np.float64(0.23973165074269204)),
 (1448, np.float64(0.239731650742692)),
 (3297, np.float64(0.23583331531828908)),
 (1924, np.float64(0.23541180771537917)),
 (1813, np.float64(0.23211917272131483)),
 (2433, np.float64(0.23211917272131483)),
 (1444, np.float64(0.22978625750451445)),
 (3848, np.float64(0.2281052820616688)),
 (2350, np.float64(0.22801181969455975)),
 (3392, np.float64(0.2250967420452386)),
 (3000, np.float64(0.22395700438234167)),
 (4308, np.float64(0.22395700438234167)),
 (1487, np.float64(0.2230128875437697)),
 (1913, np.float64(0.2228712470

In [25]:
def recommend(movie):
    movie_list_df=df[df['title'].str.contains(movie)]
    if len(movie_list_df):
        movie_index=movie_list_df.index[0]
        distance=similarity[movie_index]
        movie_list=sorted(list(enumerate(distance)),reverse=True,key=lambda x:x[1])[0:6]
        print('The recommendations for {0} :\n'.format(movie_list_df.iloc[0]['title']))
        for i in movie_list:
            print(df.iloc[i[0]].title)
    else:
        return "No Movies found"

In [27]:
recommend(input("Enter"))

The recommendations for Mad Max: Fury Road :

Mad Max: Fury Road
Mad Max
The Book of Eli
Kites
Alien Zone
Children of Men
